/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
<<<<<<< HEAD
  31337: {
    YourContract: {
      address: "0x2279B7A0a67DB372996a5FaB50D91eAA73d2eBe6",
      abi: [
        {
          inputs: [
            {
              internalType: "address",
              name: "_owner",
              type: "address",
            },
          ],
=======
  84532: {
    GrantExamp: {
      address: "0xbF54Dd38d6480EF908f33Ace05Fd5eD2237A5CE1",
      abi: [
        {
          inputs: [],
>>>>>>> 65f0de4a6c5b42e58bbf25e694655461309edcb3
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          anonymous: false,
          inputs: [
            {
<<<<<<< HEAD
              indexed: true,
              internalType: "address",
              name: "greetingSetter",
=======
              indexed: false,
              internalType: "address",
              name: "voter",
>>>>>>> 65f0de4a6c5b42e58bbf25e694655461309edcb3
              type: "address",
            },
            {
              indexed: false,
<<<<<<< HEAD
              internalType: "string",
              name: "newGreeting",
              type: "string",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "premium",
              type: "bool",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "value",
              type: "uint256",
            },
          ],
          name: "GreetingChange",
          type: "event",
        },
        {
          inputs: [],
          name: "greeting",
          outputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "owner",
          outputs: [
=======
              internalType: "uint256",
              name: "grantIndex",
              type: "uint256",
            },
          ],
          name: "VoteCast",
          type: "event",
        },
        {
          inputs: [
>>>>>>> 65f0de4a6c5b42e58bbf25e694655461309edcb3
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
<<<<<<< HEAD
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "premium",
=======
          name: "didDonate",
>>>>>>> 65f0de4a6c5b42e58bbf25e694655461309edcb3
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
<<<<<<< HEAD
              internalType: "string",
              name: "_newGreeting",
              type: "string",
            },
          ],
          name: "setGreeting",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [],
          name: "totalCounter",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
=======
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          name: "didFund",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
>>>>>>> 65f0de4a6c5b42e58bbf25e694655461309edcb3
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
<<<<<<< HEAD
          name: "userGreetingCounter",
          outputs: [
            {
=======
          name: "didVote",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "grantIndex",
              type: "uint256",
            },
          ],
          name: "getGrant",
          outputs: [
            {
              components: [
                {
                  internalType: "string",
                  name: "name",
                  type: "string",
                },
                {
                  internalType: "uint256",
                  name: "funding",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "voteCount",
                  type: "uint256",
                },
              ],
              internalType: "struct GrantExamp.Grant",
              name: "",
              type: "tuple",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
>>>>>>> 65f0de4a6c5b42e58bbf25e694655461309edcb3
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
<<<<<<< HEAD
=======
          name: "grants",
          outputs: [
            {
              internalType: "string",
              name: "name",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "funding",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "voteCount",
              type: "uint256",
            },
          ],
>>>>>>> 65f0de4a6c5b42e58bbf25e694655461309edcb3
          stateMutability: "view",
          type: "function",
        },
        {
<<<<<<< HEAD
          inputs: [],
          name: "withdraw",
=======
          inputs: [
            {
              internalType: "uint256",
              name: "grantIndex",
              type: "uint256",
            },
          ],
          name: "voteOnGrant",
>>>>>>> 65f0de4a6c5b42e58bbf25e694655461309edcb3
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
<<<<<<< HEAD
        {
          stateMutability: "payable",
          type: "receive",
=======
      ],
      inheritedFunctions: {},
    },
    ImpactEquations: {
      address: "0x0234E25474772BD5724632Ccf3ADE843fD5446EC",
      abi: [
        {
          inputs: [
            {
              internalType: "uint256[]",
              name: "R",
              type: "uint256[]",
            },
            {
              internalType: "uint256",
              name: "S",
              type: "uint256",
            },
          ],
          name: "calculateADIA",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "pure",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256[]",
              name: "R",
              type: "uint256[]",
            },
            {
              internalType: "uint256",
              name: "S",
              type: "uint256",
            },
          ],
          name: "calculateAFIA",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "pure",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256[]",
              name: "D",
              type: "uint256[]",
            },
            {
              internalType: "uint256[]",
              name: "R",
              type: "uint256[]",
            },
            {
              internalType: "uint256",
              name: "S",
              type: "uint256",
            },
          ],
          name: "calculateWDIA",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "pure",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256[]",
              name: "F",
              type: "uint256[]",
            },
            {
              internalType: "uint256[]",
              name: "R",
              type: "uint256[]",
            },
            {
              internalType: "uint256",
              name: "S",
              type: "uint256",
            },
          ],
          name: "calculateWFIA",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "pure",
          type: "function",
>>>>>>> 65f0de4a6c5b42e58bbf25e694655461309edcb3
        },
      ],
      inheritedFunctions: {},
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
